name: AlarmMaster
options:
  bundleIdPrefix: com.alarmmaster
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    INFOPLIST_FILE: AlarmMaster/Info.plist

targets:
  AlarmMaster:
    type: application
    platform: iOS
    sources:
      - AlarmMaster
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.alarmmaster.app
        CODE_SIGN_STYLE: Automatic
    info:
      path: AlarmMaster/Info.plist
      properties:
        NSUserNotificationsUsageDescription: "Alarm Master needs notification permissions to alert you when your alarms go off."
        UIBackgroundModes:
          - fetch
          - processing


